music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),
    # /music/register/
    # path('register/', views.UserFormView.as_view(), name='register'),
    # /music/51/
    path('<pk>/', views.DetailView.as_view(), name='detail'),
    # /music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),
    # /music/album/2/
    path('album/<pk>/', views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/2/delete/
    path('album/<pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),
    # /music/album/2/favorite/
    path('album/<pk>/favorite/', views.AlbumFavorite, name='album-favorite'),
    # /music/2/1/delete/
    path('<int:album_id>/<int:song_id>/delete/', views.SongDelete, name='song-delete'),
    # /music/2/add/
    path('<int:album_id>/add/', views.SongAdd.as_view(), name='song-add'),
    # /music/2/1/play
    path('<int:album_id>/<int:song_id>/play/', views.SongPlay, name='song-play'),

]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import login
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    # /user/register/
    path('register/', views.UserFormView.as_view(), name='register'),
    # /user/login/
    path('login/',views.Login.as_view(), name='login'),
    # /user/logout/
    path('logout/', views.Logout, name='logout'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('music.urls')),
    path('user/', include('user.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Album(models.Model):
    artist = models.CharField(max_length=250)
    title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    logo = models.FileField()
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    artist = models.CharField(max_length=250, default='')
    link = models.CharField(max_length=500, null=True)
    title = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.album.id})

    def __str__(self):
        return self.title


class FavoriteAlbum(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ' likes ' + self.album.title

user/models.py
from django.db import models

# Create your models here.

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

user/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
# from django.contrib.auth import authenticate, login
# from django.views.generic import View
from django.urls import reverse_lazy
from .models import Album, Song, FavoriteAlbum
# from .forms import UserForm
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'title', 'genre', 'logo']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'title', 'genre', 'logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class SongAdd(CreateView):
    model = Song
    fields = ['artist', 'title', 'link']

    def form_valid(self, form):
        a = self.kwargs['album_id']
        form.instance.album = Album.objects.get(pk=a)

        link = form.instance.link
        #link = link.replace('www.youtube.com', 'youtu.be')
        link = link.replace('watch?v=','embed/')
        form.instance.link = link

        return super().form_valid(form)


def SongPlay(request, album_id, song_id):
    messages.add_message(request, messages.INFO, 'Hello world.')
    return redirect('music:detail', album_id)
    


def SongDelete(request, album_id, song_id):
    song = Song.objects.get(pk=song_id)
    song.delete()
    return redirect('music:detail', album_id)


def AlbumFavorite(request, pk):
    album_pk = pk
    if request.user is not None:
        selected_album = Album.objects.get(pk=album_pk)
        try:
            favorite_album = request.user.favoritealbum_set.get(
                album=selected_album)
        except (KeyError, FavoriteAlbum.DoesNotExist):
            favorite = FavoriteAlbum()
            favorite.album = Album.objects.get(pk=album_pk)
            favorite.user = request.user
            favorite.save()
        else:
            favorite_album.delete()

    return redirect('music:index')


'''
class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form' : form})
	
	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			# cleaned (normalised) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			# returns User objects if credentials are correct
			user = authenticate(username=username, password=password)

			if user is not None:

				if user.is_active:
					login(request, user)
					return redirect('music:index')

		return render(request, self.template_name, {'form' : form})
'''

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, user_logged_in, views
from django.views import generic
from django.views.generic import View
from django.urls import reverse_lazy
from .forms import UserForm

# Create your views here.

def Logout(request):
	logout(request)

	return redirect('music:index')

class Login(views.LoginView):
	template_name = 'user/login.html'
	#redirect_field_name = reverse_lazy('music:index')
	#redirect_authenticated_user = True

class UserFormView(View):
	form_class = UserForm
	template_name = 'user/registration_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form' : form})
	
	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			# cleaned (normalised) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns User objects if credentials are correct
			user = authenticate(username=username, password=password)

			if user is not None:

				if user.is_active:
					login(request, user)
					return redirect('music:index')

		return render(request, self.template_name, {'form' : form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a New Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Jamsterr{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-field">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Jamsterr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>


            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    {% if user.is_authenticated %}
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    {% else %}
                        <a href="{% url 'user:register' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Register
                    {% endif %}

                    </a>
                </li>

                <li class="">
                    {% if user.is_authenticated %}
                        <a href="{% url 'user:logout' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    {% else %}
                        <a href="{% url 'user:login' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login
                    {% endif %}                
                        </a>
                </li>         
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.logo %}
                            <img src="{{ album.logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                {% if album.user == user %}<li role="presentation"><a href="{% url 'music:song-add' album.id %}">Add New Song</a></li>{% endif %}
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Artist</th>
                            <th>Audio</th>
                            <th>Favorite</th>
                            {% if album.user == user %}
                            <th>Actions</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.title }}</td>
                                <td>{{ song.artist }}</td>
                                <td>
                                        <iframe width="420" height="315"
                                        src="{{song.link}}">
                                        </iframe>
                                    <!--<a target="_blank" href="{% url 'music:song-play' song.album.id song.id%}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a> -->
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                {% if album.user == user %}
                                <td>
                                    <form action="{% url 'music:song-delete' song.album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>

                                </td>
                                {% endif %}
                                <!--<td>
                                    <iframe width="420" height="315"
                                    src="{{song.link}}">
                                    </iframe></td> -->
                            </tr>

                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"> {{ field.error }} </span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10"> {{ field }} </div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% load music_extras %}
{% block albums_active %}active{% endblock %}


{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Hey, <b>{{ user.username }}</b></h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.title }} - <p>{{ album.artist }}</p></h2>
                            <h4>{{ album.user.username }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            {% if album.user == user %}
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            {% endif %}

                            <!-- Favorite Album -->
                            <a href="{% url 'music:album-favorite' album.id %}" class="btn btn-default btn-sm btn-favorite" onClick="window.location.reload()">
                                {% check_if_favorite user album.id as x %}
                                {% with album.favoritealbum_set.count as n %}
                                <span class="glyphicon glyphicon-star{% if x is None %}-empty{% endif %}">{% if x is not None %} <b>{{n}}</b> {% else %} {{n}} {% endif %}</span>
                                {% endwith %}
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.logo }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:album-favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> Create a New Account </h3>
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %} Add a New Song {% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

user/templates/user/login.html
{% extends 'music/base.html' %}
{% block title %} Login {% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> Login </h3>
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

user/templates/user/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> Create a New Account </h3>
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}